const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const { test } = require('node:test');
const { chromium } = require('@playwright/test');
Object.assign(process.env,{DATA_DIR:fs.mkdtempSync(path.join(os.tmpdir(),'autotrade-browser-')),AI_PROVIDER:'ollama',AI_API_KEY:'test',HEADLESS:'1',BROKER:'alpaca',API_TOKEN:'browser-test-internal-token-12345678'});
require('ts-node/register');
const { config }=require('../src/core/config');config.api.port=0;
const { HeadlessUI }=require('../src/ui/headless');
const { startApiServer }=require('../src/server/api');
const { setUser }=require('../src/server/auth');
const { loadPolicy, getPolicySnapshot }=require('../src/policy/load');
const { updateState,getState }=require('../src/state/state');
const { createProposal }=require('../src/core/proposals');
const { closeStorage }=require('../src/core/storage');
const { recordTick }=require('../src/features/lastTick');

test('browser login, approvals, saved strategy, pause and mobile layout',async()=>{
  loadPolicy();updateState({accountId:'alpaca:paper:demo-account'});
  setUser('demo-admin','admin','demo-password-for-testing-only');
  const ui=new HeadlessUI();ui.setEnvironment({broker:'alpaca',venue:'paper',provider:'ollama',model:'test',gate:'manual'});
  ui.registerCommand({name:'pause',help:'Pause',run:()=>updateState({paused:true})});
  const p=createProposal({kind:'entry',symbol:'AAPL',venue:'paper',params:{qty:2,signal:{price:100,stopLoss:95,takeProfit:110}},reason:'Test proposal for browser verification',timeoutMs:600000});
  recordTick({tickAt:new Date().toISOString(),positionsStale:false,ordersStale:false,positions:{MSFT:{symbol:'MSFT',qty:3,entryPrice:410,price:415,stopLevel:null}},orders:[],watchlist:{},account:{equity:100000,cash:98000},portfolio:{},session:'open'});
  ui.reply('Your account is ready for review.');
  const lessons=require('../src/journal/lessons');lessons.recordLesson('Review concentration before adding exposure.');
  require('../src/core/commands').enqueueCommand('trader','Review managed holdings','demo-admin');
  const server=startApiServer({ui,trader:{status:{paused:false}}});
  let browser;
  try {
    await new Promise(resolve=>setTimeout(resolve,30));
    const base='http://127.0.0.1:'+server.address().port;config.api.publicOrigin=base;
    const chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
    browser=await chromium.launch({headless:true,...(fs.existsSync(chrome)?{executablePath:chrome}:{})});
    const context=await browser.newContext({viewport:{width:1440,height:1000}});
    const page=await context.newPage(),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
    await page.goto(base);
    await page.getByLabel('Username',{exact:true}).fill('demo-admin');
    await page.getByLabel('Password',{exact:true}).fill('demo-password-for-testing-only');
    await page.getByRole('button',{name:'Sign in',exact:true}).click();
    await page.locator('#workspace').waitFor({state:'visible'});
    await page.getByRole('button',{name:'Approve action'}).click();
    await page.waitForFunction(()=>document.querySelector('#proposals').textContent.includes('approved'));
    assert.equal(getState().proposals[p.id].actorId,'demo-admin');
    await page.getByRole('button',{name:'Pause trading',exact:true}).click();
    await page.getByRole('button',{name:'Resume trading',exact:true}).waitFor();assert.equal(getState().paused,true);
    await page.getByLabel('Maximum positions',{exact:true}).fill('2');
    const profileRevision=getPolicySnapshot().hash;
    await page.getByLabel('Profile',{exact:true}).selectOption('conservative');
    assert.equal(await page.getByLabel('Risk per trade (% of equity)',{exact:true}).inputValue(),'0.25');
    assert.equal(await page.getByLabel('Portfolio volatility target (% per year)',{exact:true}).inputValue(),'8');
    assert.equal(await page.getByLabel('Maximum position size (%)',{exact:true}).inputValue(),'5');
    assert.equal(getPolicySnapshot().hash,profileRevision,'editing a preset does not activate it');
    await page.getByLabel('Risk per trade (% of equity)',{exact:true}).fill('0.35');
    assert.equal(await page.getByLabel('Profile',{exact:true}).inputValue(),'custom');
    await page.getByRole('button',{name:'Review and save',exact:true}).click();
    assert.match(await page.locator('#review-text').textContent(),/Risk per trade: 0.5% → 0.35%/);
    await page.getByRole('button',{name:'Save this revision',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#settings-state').textContent==='Saved');
    assert.equal(getPolicySnapshot().policy.risk.riskPerTradePct,0.35);
    assert.equal(getPolicySnapshot().policy.risk.targetVolatilityPct,8);
    await page.getByRole('button',{name:'Reload saved settings',exact:true}).click();
    assert.equal(await page.getByLabel('Profile',{exact:true}).inputValue(),'custom');
    await page.locator('.risk-profile').screenshot({path:'/tmp/autotrade-risk-profile-desktop.png'});
    await page.locator('#lesson-list textarea').fill('Review measured concentration before adding exposure.');
    await page.locator('#lesson-list').getByRole('button',{name:'Save',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#lesson-list textarea').value.startsWith('Review measured'));
    await page.locator('#lesson-list').getByRole('button',{name:'Retire',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#lesson-list').textContent.includes('Retired'));
    assert.equal(lessons.listLessons()[0].active,false);
    assert.match(await page.locator('#agent-commands').textContent(),/demo-admin/);
    await page.locator('#message-text').fill('What is the request status?');
    await page.locator('#message').getByRole('button',{name:'Send',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('queued'));
    await page.screenshot({path:'/tmp/autotrade-desktop.png',fullPage:true});
    const mobile=await page.context().newPage();
    await mobile.setViewportSize({width:390,height:844});
    await mobile.goto(base);
    await mobile.locator('#workspace').waitFor({state:'visible'});
    await mobile.waitForTimeout(500);
    await mobile.screenshot({path:'/tmp/autotrade-mobile.png'});
    await mobile.locator('#holdings').screenshot({path:'/tmp/autotrade-mobile-holdings.png'});
    await mobile.locator('#lessons').screenshot({path:'/tmp/autotrade-mobile-lessons.png'});
    await mobile.locator('.risk-profile').screenshot({path:'/tmp/autotrade-risk-profile-mobile.png'});
    assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    await mobile.close();
    assert.deepEqual(errors,[]);
    await page.getByRole('button',{name:'Sign out'}).click();
    await page.locator('#login-panel').waitFor({state:'visible'});
  } finally {await browser?.close();await server.close();closeStorage();}
});
