const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const { test } = require('node:test');
const { chromium, expect } = require('@playwright/test');
Object.assign(process.env,{DATA_DIR:fs.mkdtempSync(path.join(os.tmpdir(),'autotrade-browser-')),AI_PROVIDER:'ollama',AI_API_KEY:'test',HEADLESS:'1',BROKER:'alpaca'});
require('ts-node/register');
const { config }=require('../src/core/config');config.api.port=0;
const { HeadlessUI }=require('../src/ui/headless');
const { startApiServer }=require('../src/server/api');
const { loadPolicy, getPolicySnapshot }=require('../src/policy/load');
const { updateState,getState }=require('../src/state/state');
const { createAction }=require('../src/core/actions');
const { closeStorage }=require('../src/core/storage');
const { recordTick }=require('../src/features/lastTick');

test('dashboard without login: approvals, saved strategy, pause and mobile layout',async()=>{
  loadPolicy();updateState({accountId:'alpaca:paper:demo-account'});
  const ui=new HeadlessUI();ui.setEnvironment({broker:'alpaca',venue:'paper',provider:'ollama',model:'test',gate:'manual'});
  const commandRuns=[];
  ui.registerCommand({name:'pause',api:true,help:'Pause trading. Existing broker orders remain active.',run:()=>{commandRuns.push('pause');updateState({paused:true});}});
  ui.registerCommand({name:'positions',api:true,aliases:['pos'],help:'Every open position with stop, target and P&L.',run:()=>{commandRuns.push('positions');ui.reply('Positions command complete.');}});
  ui.registerCommand({name:'lessons',api:true,args:'[n]',help:'Show the last n lessons.',run:args=>{commandRuns.push('lessons '+args);ui.reply('Lessons requested: '+args);}});
  ui.registerCommand({name:'quit',help:'Local only',run:()=>assert.fail('Local command executed')});
  const p=createAction({kind:'entry',symbol:'AAPL',venue:'paper',params:{qty:2,signal:{price:100,stopLoss:95,takeProfit:110}},reason:'Test action for browser verification',timeoutMs:600000});
  recordTick({tickAt:new Date().toISOString(),positionsStale:false,ordersStale:false,positions:{MSFT:{symbol:'MSFT',qty:3,entryPrice:410,price:415,stopLevel:null}},orders:[],watchlist:{},account:{equity:100000,cash:98000},portfolio:{},session:'open'});
  ui.reply('Your account is ready for review.');
  const lessons=require('../src/journal/lessons');lessons.recordLesson('Review concentration before adding exposure.');
  require('../src/core/requests').enqueueRequest('trader','Review managed holdings','operator');
  const server=startApiServer({ui,trader:{status:{paused:false}}});
  let browser;
  try {
    await new Promise(resolve=>setTimeout(resolve,30));
    const base='http://127.0.0.1:'+server.address().port;
    const chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
    browser=await chromium.launch({headless:true,...(fs.existsSync(chrome)?{executablePath:chrome}:{})});
    const context=await browser.newContext({viewport:{width:1440,height:1000}});
    const page=await context.newPage(),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
    await page.goto(base);
    await page.locator('#workspace').waitFor({state:'visible'});
    await page.getByRole('button',{name:'Approve action'}).click();
    await page.waitForFunction(()=>document.querySelector('#actions').textContent.includes('approved'));
    assert.equal(require('../src/core/actions').getAction(p.id).actorId,'operator');
    await page.getByRole('button',{name:'Pause trading',exact:true}).click();
    await page.getByRole('button',{name:'Resume trading',exact:true}).waitFor();assert.equal(getState().paused,true);
    await page.getByLabel('Maximum positions',{exact:true}).fill('2');
    const profileRevision=getPolicySnapshot().hash;
    await page.getByLabel('Profile',{exact:true}).selectOption('conservative');
    assert.equal(await page.getByLabel('Risk per trade (% of equity)',{exact:true}).inputValue(),'0.25');
    assert.equal(await page.getByLabel('Portfolio volatility target (% per year)',{exact:true}).inputValue(),'8');
    assert.equal(await page.getByLabel('Maximum position size (%)',{exact:true}).inputValue(),'5');
    assert.equal(getPolicySnapshot().hash,profileRevision,'editing a preset does not activate it');
    await page.getByLabel('Risk per trade (% of equity)',{exact:true}).fill('0.35');
    assert.equal(await page.getByLabel('Profile',{exact:true}).inputValue(),'custom');
    await page.getByRole('button',{name:'Review and save',exact:true}).click();
    assert.match(await page.locator('#review-text').textContent(),/Risk per trade: 0.5% → 0.35%/);
    await page.getByRole('button',{name:'Save this revision',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#settings-state').textContent==='Saved');
    assert.equal(getPolicySnapshot().policy.risk.riskPerTradePct,0.35);
    assert.equal(getPolicySnapshot().policy.risk.targetVolatilityPct,8);
    await page.getByRole('button',{name:'Reload saved settings',exact:true}).click();
    assert.equal(await page.getByLabel('Profile',{exact:true}).inputValue(),'custom');
    await page.locator('.risk-profile').screenshot({path:'/tmp/autotrade-risk-profile-desktop.png'});
    await page.locator('#lesson-list textarea').fill('Review measured concentration before adding exposure.');
    await page.locator('#lesson-list').getByRole('button',{name:'Save',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#lesson-list textarea').value.startsWith('Review measured'));
    await page.locator('#lesson-list').getByRole('button',{name:'Retire',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#lesson-list').textContent.includes('Retired'));
    assert.equal(lessons.listLessons()[0].active,false);
    assert.match(await page.locator('#agent-commands').textContent(),/operator/);
    await page.locator('#message-text').fill('What is the request status?');
    await page.locator('#message').getByRole('button',{name:'Send',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('queued'));
    const input=page.getByRole('combobox',{name:'Message'}),menu=page.getByRole('listbox',{name:'Commands'});
    const queuedBefore=require('../src/core/requests').listRequests().length;
    await input.fill('/');
    await expect(menu).toBeVisible();
    await expect(menu.getByRole('option')).toHaveCount(4);
    await expect(input).toHaveAttribute('aria-expanded','true');
    await input.press('ArrowDown');
    await expect(menu.getByRole('option',{selected:true})).toContainText('/pause');
    await input.press('Enter');
    await expect(input).toHaveValue('/pause ');
    await expect(menu).toBeHidden();
    assert.deepEqual(commandRuns,['pause'],'selecting does not run the command');
    await input.fill('/LE');
    await expect(menu.getByRole('option')).toHaveCount(1);
    await expect(menu).toContainText('/lessons [n]');
    await input.press('Tab');
    await expect(input).toHaveValue('/lessons ');
    await expect(input).toBeFocused();
    await input.pressSequentially('2');
    await expect(menu).toBeHidden();
    await input.press('Enter');
    await expect(input).toHaveValue('');
    await expect(page.locator('#feed')).toContainText('Lessons requested: 2');
    assert.equal(commandRuns.at(-1),'lessons 2');
    await input.fill('/pos');
    await expect(menu.getByRole('option')).toHaveCount(1);
    await input.press('Escape');
    await expect(menu).toBeHidden();
    await expect(input).toHaveValue('/pos');
    await input.press('ArrowDown');
    await menu.getByRole('option').click();
    await expect(input).toHaveValue('/positions ');
    await input.press('Enter');
    await expect(page.locator('#feed')).toContainText('Positions command complete.');
    await input.fill('/');
    await input.press('ArrowUp');
    await expect(menu.getByRole('option',{selected:true})).toContainText('/lessons');
    await input.press('Escape');
    await input.fill('What does /pause do?');
    await expect(menu).toBeHidden();
    await input.fill('/unknown');
    await expect(page.locator('#command-empty')).toBeVisible();
    await input.press('Enter');
    await expect(page.locator('#notice')).toContainText('Unknown or unavailable command');
    await expect(input).toHaveValue('/unknown');
    assert.equal(require('../src/core/requests').listRequests().length,queuedBefore,'slash commands never enter the concierge queue');
    await input.fill('/');
    await page.locator('#activity').screenshot({path:'/tmp/autotrade-slash-commands-desktop.png'});
    await input.press('Tab');
    await page.screenshot({path:'/tmp/autotrade-desktop.png',fullPage:true});
    const mobileContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,storageState:await context.storageState()});
    const mobile=await mobileContext.newPage();
    await mobile.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
    await mobile.goto(base);
    await mobile.locator('#workspace').waitFor({state:'visible'});
    await mobile.waitForTimeout(500);
    await mobile.screenshot({path:'/tmp/autotrade-mobile.png'});
    await mobile.locator('#holdings').screenshot({path:'/tmp/autotrade-mobile-holdings.png'});
    await mobile.locator('#lessons').screenshot({path:'/tmp/autotrade-mobile-lessons.png'});
    await mobile.locator('.risk-profile').screenshot({path:'/tmp/autotrade-risk-profile-mobile.png'});
    await mobile.locator('#message-text').fill('/');
    await expect(mobile.getByRole('listbox',{name:'Commands'})).toBeVisible();
    await mobile.locator('#activity').screenshot({path:'/tmp/autotrade-slash-commands-mobile.png'});
    assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    await mobile.getByRole('option').filter({hasText:'/positions'}).tap();
    await expect(mobile.locator('#message-text')).toHaveValue('/positions ');
    await expect(mobile.getByRole('listbox',{name:'Commands'})).toBeHidden();
    await mobileContext.close();
    assert.deepEqual(errors,[]);
  } finally {await browser?.close();await server.close();closeStorage();}
});
