const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const { test } = require('node:test');
const { chromium, expect } = require('@playwright/test');
Object.assign(process.env,{DATA_DIR:fs.mkdtempSync(path.join(os.tmpdir(),'autotrade-browser-')),AI_PROVIDER:'ollama',AI_API_KEY:'test',HEADLESS:'1',BROKER:'alpaca'});
require('ts-node/register');
const { config }=require('../src/core/config');config.api.port=0;
const { HeadlessUI }=require('../src/ui/headless');
const { startApiServer }=require('../src/server/api');
const { loadPolicy, getPolicySnapshot }=require('../src/policy/load');
const { updateState,getState }=require('../src/state/state');
const { createAction }=require('../src/core/actions');
const { closeStorage }=require('../src/core/storage');
const { recordTick }=require('../src/features/lastTick');
const { agentContext }=require('../src/core/agentContext');
const asAssistant = fn => agentContext.run({ role: 'assistant', requestId: 'browser-chat', actorId: 'operator' }, fn);

test('conversation tool calls expand complete inputs and outputs without losing state on updates', async () => {
  require('../src/core/storage').resetStorage();
  loadPolicy();updateState({ accountId: 'alpaca:paper:tool-chat' });
  const ui = new HeadlessUI();
  const input = { symbol: 'IBM', query: '<img src=x onerror=alert(1)>', nested: { flags: [true, false] } };
  const output = JSON.stringify({ points: Array.from({ length: 800 }, (_, i) => ({ value: i, note: 'complete observation' })), end: 'last output value' });
  const tool = { id: 'chat-tool-1', requestId: 'chat-request', agent: 'assistant', name: 'get_bars', input, output };
  ui.echoOperator('How is my portfolio doing?');
  ui.log('TOOL', '[assistant] get_bars(symbol=IBM) → 800 bars', tool);
  require('../src/core/agentContext').agentContext.run({ role: 'assistant', requestId: 'chat-request', actorId: 'operator' }, () => ui.reply('Your portfolio is **lightly invested**, with two open positions.\n\nI can walk you through the current exposure and the trader’s latest decision.'));
  ui.reply('Paper account connected.');
  ui.log('INFO', 'Market data refreshed.');
  ui.alert('IBM price data is stale.');
  asAssistant(() => ui.log('INFO', 'Reviewing your portfolio question.'));
  const server = startApiServer({ ui, trader: { status: { paused: false } } });
  let browser;
  try {
    await new Promise(resolve => setTimeout(resolve, 30));
    const base = 'http://127.0.0.1:' + server.address().port;
    const chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
    browser = await chromium.launch({ headless: true, ...(fs.existsSync(chrome) ? { executablePath: chrome } : {}) });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];page.on('pageerror', error => errors.push(error.message));
    await page.route('**/*', route => route.request().url().startsWith(base) ? route.continue() : route.abort());
    await page.goto(base);
    const calls = page.locator('#feed .tool-call'), first = calls.first();
    await expect(first).toBeVisible();
    await expect(first.locator('summary .tool-call-agent')).toHaveText('Assistant');
    await expect(first).toHaveAttribute('data-source', 'assistant');
    await expect(first.locator('.tool-call-type')).toHaveText('Tool result');
    await expect(page.locator('#feed .operator .message-author')).toHaveText('You');
    await expect(page.locator('#feed .reply[data-source="assistant"] .message-author')).toHaveText('Assistant');
    await expect(page.locator('#feed .reply[data-source="assistant"] .message-type')).toHaveText('Assistant');
    await expect(page.locator('#live-feed .activity-entry.operator .activity-entity')).toHaveText('You');
    await expect(page.locator('#live-feed .activity-entry.operator .activity-kind')).toHaveText('[MESSAGE]');
    await expect(page.locator('#live-feed .activity-entry.tool .activity-entity')).toHaveText('Assistant');
    await expect(page.locator('#live-feed .activity-entry.tool .activity-kind')).toHaveText('[TOOL]');
    await expect(page.locator('#feed [data-source="system"]')).toHaveCount(0);
    for (const message of ['Paper account connected.', 'Market data refreshed.', 'IBM price data is stale.', 'Reviewing your portfolio question.']) {
      await expect(page.locator('#live-feed')).toContainText(message);
      await expect(page.locator('#feed')).not.toContainText(message);
    }
    await expect(page.locator('#feed .log')).toBeHidden();
    await page.locator('#show-log').check();
    await expect(page.locator('#feed .log')).toHaveCount(0);
    await expect(page.locator('#feed')).not.toContainText('Reviewing your portfolio question.');
    await expect(page.locator('#feed [data-source="system"]')).toHaveCount(0);
    ui.reply('Account sync complete.');
    await expect(page.locator('#live-feed')).toContainText('Account sync complete.');
    await expect(page.locator('#feed')).not.toContainText('Account sync complete.');
    await page.locator('#show-log').uncheck();
    await expect(first.locator('summary .tool-call-params')).toContainText('symbol="IBM"');
    await expect(first.locator('summary .tool-call-params')).toContainText('nested={"flags":[true,false]}');
    await expect(first.locator('summary img')).toHaveCount(0);
    await expect(page.locator('#show-log')).not.toBeChecked();
    await expect(page.locator('#welcome')).toBeHidden();
    assert.equal(await first.evaluate(el => el.open), false);
    assert.ok((await first.boundingBox()).height < 40, 'collapsed call remains one compact row');
    await first.locator('summary').focus();await first.locator('summary').press('Enter');
    await expect(first.locator('pre')).toHaveCount(2);
    await expect(first.locator('pre').first()).toHaveText(JSON.stringify(input, null, 2));
    assert.equal(await first.locator('pre').last().textContent(), JSON.stringify(JSON.parse(output), null, 2));
    await expect(first.locator('img')).toHaveCount(0);
    await page.evaluate(() => refresh());
    assert.equal(await first.evaluate(el => el.open), true, 'polling preserves expanded calls');
    ui.log('TOOL', '[trader] inspect_order() → error', { id: 'chat-tool-2', agent: 'trader', name: 'inspect_order', input: {}, output: '{"ok":false,"error":"Order unavailable"}' });
    await expect(calls).toHaveCount(2);
    await expect(calls.last().locator('summary')).toContainText('Error');
    await expect(calls.last().locator('summary .tool-call-agent')).toHaveText('Trader');
    await expect(calls.last()).toHaveAttribute('data-source', 'trader');
    await expect(page.locator('#live-feed .activity-entry.tool').last().locator('.activity-entity')).toHaveText('Trader');
    await expect(calls.last().locator('summary .tool-call-params')).toHaveText('()');
    assert.equal(await first.evaluate(el => el.open), true, 'new live tool calls preserve expanded calls');
    ui.log('TOOL', '[assistant] text_tool() → plain text', { agent: 'assistant', name: 'text_tool', input: null, output: 'Plain text\n<output> is literal' });
    await expect(calls).toHaveCount(3);await calls.last().locator('summary').click();
    await expect(calls.last().locator('pre').last()).toHaveText('Plain text\n<output> is literal');
    asAssistant(() => ui.log('TOOL', '[assistant] legacy_tool() → old summary'));
    await expect(calls).toHaveCount(4);await calls.last().locator('summary').click();
    await expect(calls.last().locator('summary .tool-call-agent')).toHaveText('Assistant');
    await expect(calls.last()).toContainText('Full input and output were not saved');
    await page.reload();
    await expect(calls).toHaveCount(4);
    await expect(page.locator('#feed [data-source="system"]')).toHaveCount(0);
    await expect(page.locator('#live-feed')).toContainText('Account sync complete.');
    assert.equal(await first.evaluate(el => el.open), false);
    await page.setViewportSize({ width: 390, height: 844 });
    await first.locator('summary').click();
    await expect(first.locator('pre').last()).toContainText('last output value');
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await first.screenshot({ path: '/tmp/autotrade-chat-tool-mobile.png' });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await first.screenshot({ path: '/tmp/autotrade-chat-tool-desktop.png' });
    await page.locator('#show-log').check();
    const ackInput = { id: 'ema_cross_down:AMZN:test', disposition: 'acknowledged', note: 'AMZN remains above its recorded stop.' };
    const ackSummary = `[TraderTool] ack ${ackInput.id} — acknowledged: ${ackInput.note}`;
    agentContext.run({ role: 'trader', requestId: 'ack-request', actorId: 'system' }, () => {
      ui.log('INFO', ackSummary);
      ui.log('TOOL', '[trader] ack_event() → acknowledged', { id: 'ack-call', agent: 'trader', name: 'ack_event', input: ackInput, output: '{"ok":true}' });
    });
    await expect(calls).toHaveCount(5);
    await expect(calls.last().locator('.tool-call-name')).toHaveText('ack_event');
    await expect(calls.last().locator('.tool-call-params')).toContainText(ackInput.note);
    await expect(page.locator('#feed')).not.toContainText(ackSummary);
    await expect(page.locator('#live-feed .activity-entry.info').filter({ hasText: ackSummary })).toHaveCount(1);
    await expect(page.locator('#live-feed .activity-entry.tool').filter({ hasText: 'ack_event' })).toHaveCount(1);
    await page.reload();
    await expect(calls).toHaveCount(5);
    await expect(page.locator('#show-log')).toBeChecked();
    await expect(page.locator('#feed .log.level-info')).toHaveCount(0);
    await expect(page.locator('#feed')).not.toContainText(ackSummary);
    await expect(page.locator('#live-feed')).toContainText(ackSummary);
    await page.getByRole('button', { name: 'Clear conversation', exact: true }).click();
    await expect(calls).toHaveCount(0);
    await page.locator('#show-log').check();
    ui.log('INFO', 'Background account refresh complete.');
    await expect(page.locator('#live-feed')).toContainText('Background account refresh complete.');
    await expect(page.locator('#welcome')).toBeVisible();
    await expect(page.locator('#feed .msg')).toHaveCount(0);
    await page.reload();await expect(page.locator('#live')).toHaveText('Live');
    await expect(calls).toHaveCount(0);
    await expect(page.locator('#feed .msg')).toHaveCount(0);
    assert.deepEqual(errors, []);
  } finally { await browser?.close();await server.close();require('../src/core/storage').resetStorage(); }
});

test('terminal activity preserves full events and scroll position while bounded scrollback fills', async () => {
  const storage = require('../src/core/storage');storage.resetStorage();
  loadPolicy();updateState({ accountId: 'alpaca:paper:terminal-log' });
  const ui = new HeadlessUI();
  for (let index = 0; index < 40; index++) storage.appendActivity({
    at: new Date(Date.now() - (40 - index) * 1000).toISOString(), kind: 'log', level: 'INFO', text: `Market update ${index + 1}`,
  });
  const server = startApiServer({ ui, trader: { status: { paused: false } } });
  let browser;
  try {
    await new Promise(resolve => setTimeout(resolve, 30));
    const base = 'http://127.0.0.1:' + server.address().port;
    const chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
    browser = await chromium.launch({ headless: true, ...(fs.existsSync(chrome) ? { executablePath: chrome } : {}) });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];page.on('pageerror', error => errors.push(error.message));
    await page.route('**/*', route => route.request().url().startsWith(base) ? route.continue() : route.abort());
    await page.goto(base);
    const feed = page.locator('#live-feed'), rows = feed.locator('.activity-entry');
    const bottomGap = () => feed.evaluate(el => el.scrollHeight - el.scrollTop - el.clientHeight);
    await expect(rows).toHaveCount(40);
    await expect(page.locator('#live')).toHaveText('Live');
    await expect(rows.first().locator('time')).toHaveText(/^\d{2}:\d{2}:\d{2}$/);
    await expect(rows.first().locator('.activity-entity')).toHaveText('System');
    await expect(rows.first().locator('.activity-kind')).toHaveText('[INFO]');
    assert.ok(await bottomGap() < 2, 'initial history follows the newest event');
    ui.log('WARN', 'Quote is stale; waiting for a fresh price.');
    await expect(rows).toHaveCount(41);
    await expect(rows.last()).toContainText('[WARN]');
    assert.ok(await bottomGap() < 2, 'live events follow the bottom');

    await feed.evaluate(el => { el.scrollTop = 0; });
    const multiline = 'Review started\nChecking holdings\nChecking orders\nChecking limits\n<img src=x onerror=alert(1)>\nReview complete';
    ui.reply(multiline);
    await expect(rows).toHaveCount(42);
    assert.equal(await feed.evaluate(el => el.scrollTop), 0, 'new events leave older lines in place');
    await expect(rows.last().locator('p')).toHaveText(multiline);
    await expect(rows.last().locator('img')).toHaveCount(0);
    assert.ok(await rows.last().locator('p').evaluate(el => el.clientHeight >= el.scrollHeight), 'multiline events are fully visible without clamping');

    // Replay batches exercise the same renderer used for startup and reconnect catch-up.
    const appendBatch = count => page.evaluate(count => {
      const after = cursor;
      const samples = [['INFO', 'Market snapshot refreshed.'], ['INFO', 'Checking portfolio exposure.'],
        ['TOOL', '[trader] get_positions() → 2 positions'], ['INFO', 'Risk limits checked.'],
        ['TRADE', 'Broker order confirmed.'], ['WARN', 'Waiting for a fresh quote.']];
      addEntries(Array.from({ length: count }, (_, index) => {
        const [level, body] = samples[index % samples.length];
        return { seq: after + index + 1, at: new Date().toISOString(), kind: 'log', level, text: `${body} Event ${after + index + 1}` };
      }));
    }, count);
    await appendBatch(950);
    await expect(rows).toHaveCount(992);
    await feed.evaluate(el => { el.scrollTop = 600; });
    const visibleLine = () => feed.evaluate(el => {
      const top = el.getBoundingClientRect().top;
      const row = [...el.querySelectorAll('.activity-entry')].find(row => row.getBoundingClientRect().top >= top);
      return { seq: row.dataset.seq, offset: row.getBoundingClientRect().top - top };
    });
    const beforeTrim = await visibleLine();
    await appendBatch(20);
    await expect(rows).toHaveCount(1000);
    const afterTrim = await visibleLine();
    assert.equal(afterTrim.seq, beforeTrim.seq, 'trimming old scrollback preserves the line being read');
    assert.ok(Math.abs(afterTrim.offset - beforeTrim.offset) < 1, 'the visible line stays at the same position');
    const sequences = await rows.evaluateAll(rows => rows.map(row => Number(row.dataset.seq)));
    assert.equal(new Set(sequences).size, sequences.length);
    assert.deepEqual(sequences, [...sequences].sort((a, b) => a - b));
    await feed.evaluate(el => { el.scrollTop = el.scrollHeight; });
    await appendBatch(1);
    assert.ok(await bottomGap() < 2, 'returning to the bottom resumes following');
    await page.getByRole('button', { name: 'Clear conversation', exact: true }).click();
    await expect(rows).toHaveCount(1000);

    await page.locator('#live-activity').screenshot({ path: '/tmp/autotrade-terminal-log-desktop.png' });
    await page.getByRole('button', { name: 'Switch to light theme' }).click();
    await page.locator('#live-activity').screenshot({ path: '/tmp/autotrade-terminal-log-light.png' });
    await page.getByRole('button', { name: 'Switch to dark theme' }).click();
    for (const width of [390, 320]) {
      await page.setViewportSize({ width, height: 844 });
      await feed.evaluate(el => { el.scrollTop = el.scrollHeight; });
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      assert.ok(await feed.evaluate(el => el.scrollWidth <= el.clientWidth), 'activity columns fit the mobile log viewport');
      await page.locator('#live-activity').screenshot({ path: `/tmp/autotrade-terminal-log-${width}.png` });
      await page.locator('.chat-heading').screenshot({ path: `/tmp/autotrade-chat-heading-${width}.png` });
    }
    assert.deepEqual(errors, []);
  } finally { await browser?.close();await server.close();storage.resetStorage(); }
});

test('dashboard without login: approvals, saved strategy, pause and mobile layout',async()=>{
  loadPolicy();updateState({accountId:'alpaca:paper:demo-account'});
  const ui=new HeadlessUI();ui.setEnvironment({broker:'alpaca',venue:'paper',provider:'ollama',model:'test',gate:'manual'});
  const commandRuns=[];
  ui.registerCommand({name:'pause',api:true,help:'Pause trading. Existing broker orders remain active.',run:()=>{commandRuns.push('pause');updateState({paused:true});}});
  ui.registerCommand({name:'positions',api:true,aliases:['pos'],help:'Every open position with stop, target and P&L.',run:()=>{commandRuns.push('positions');ui.reply('Positions command complete.');}});
  ui.registerCommand({name:'lessons',api:true,args:'[n]',help:'Show the last n lessons.',run:args=>{commandRuns.push('lessons '+args);ui.reply('Lessons requested: '+args);}});
  ui.registerCommand({name:'quit',help:'Local only',run:()=>assert.fail('Local command executed')});
  const p=createAction({kind:'entry',symbol:'AAPL',venue:'paper',params:{qty:2,signal:{price:100,stopLoss:95,takeProfit:110}},reason:'Test action for browser verification',timeoutMs:600000});
  require('../src/review/fills').recordFills([{execId:'browser-fill',orderId:'browser-order',permId:null,symbol:'AAPL',side:'buy',qty:0.5,price:100.125,fee:null,at:new Date().toISOString()}]);
  const event={id:'entry_signal:WMT:2026-10-08T15:11:29.647Z',kind:'entry_signal',symbol:'WMT',severity:'urgent',firedAt:'2026-10-08T15:11:29.647Z',headline:'WMT entry signal',evidence:{price:109.78,composite:0.21},policyVersion:47,cooldownKey:'entry_signal:WMT',suggestedAction:'research',ackedAt:null,ackDisposition:'acknowledged',ackNote:'The plan is below the required reward:risk.',handling:'observed',wakeCount:1};
  const resolved={...event,id:'position_drop:LLY:2026-10-08T13:39:11.778Z',kind:'position_drop',symbol:'LLY',firedAt:'2026-10-08T13:39:11.778Z',headline:'LLY position drop',cooldownKey:'position_drop:LLY',handling:'resolved',ackedAt:'2026-10-08T14:04:59Z',ackNote:'Position already closed.'};
  require('../src/features/alertLog').appendAlertLog(event);require('../src/features/alertLog').appendAlertLog(resolved);
  require('../src/core/storage').saveValue('eventRegistry',{pending:[event],live:[event]});
  const usageDay=new Date().toISOString().slice(0,10);
  require('../src/core/storage').saveValue('modelUsage:'+usageDay,{day:usageDay,requests:3,inputTokens:1400,outputTokens:100,missingUsage:0,byAgent:{trader:{requests:2,inputTokens:1200,outputTokens:80,missingUsage:0},assistant:{requests:1,inputTokens:200,outputTokens:20,missingUsage:0}}});
  const tick=(equity,price)=>recordTick({tickAt:new Date().toISOString(),positionsStale:false,ordersStale:false,positions:{MSFT:{symbol:'MSFT',qty:3,entryPrice:410,price,stopLevel:null}},orders:[],watchlist:{AAPL:{symbol:'AAPL',price:100}},account:{equity,cash:98000},portfolio:{},session:'open'});
  tick(100000,415);

  const lessons=require('../src/journal/lessons');lessons.recordLesson('Review concentration before adding exposure.');
  require('../src/core/requests').enqueueRequest('trader','Review managed holdings','operator');
  const server=startApiServer({ui,trader:{status:{paused:false}}});
  let browser;
  try {
    await new Promise(resolve=>setTimeout(resolve,30));
    const base='http://127.0.0.1:'+server.address().port;
    const chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
    browser=await chromium.launch({headless:true,...(fs.existsSync(chrome)?{executablePath:chrome}:{})});
    const context=await browser.newContext({viewport:{width:1440,height:1000}});
    const page=await context.newPage(),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
    const chartRoute=route=>{const url=new URL(route.request().url());return route.fulfill({json:{symbol:url.searchParams.get('symbol'),timeframe:url.searchParams.get('timeframe'),available:true,source:'alpaca',stale:false,asOf:'2026-10-07T14:00:00Z',bars:[{t:'2026-10-05T14:00:00Z',o:100,h:104,l:99,c:103,v:2000},{t:'2026-10-06T14:00:00Z',o:103,h:105,l:100,c:101,v:2400},{t:'2026-10-07T14:00:00Z',o:101,h:107,l:100,c:106,v:3000}]}});};
    await page.route('**/api/price-history?**',chartRoute);
    await page.goto(base);
    await page.locator('#workspace').waitFor({state:'visible'});
    await expect(page.locator('#live')).toHaveText('Live');
    await expect(page.locator('#current-agents')).toContainText('Trader');
    await expect(page.locator('.sidebar')).not.toContainText('YOUR AGENTS');
    await expect(page.locator('#agent-usage')).toHaveCount(0);
    await expect(page.locator('.agent-tokens')).toHaveCount(3);
    await expect(page.locator('.agent-tokens').first()).toHaveText('(in 1,200 / out 80)');
    await expect(page.locator('.agent-tokens').nth(1)).toHaveText('(in 200 / out 20)');
    await expect(page.locator('#current-agents')).toContainText('Research');
    await expect(page.locator('.agent-tokens').last()).toHaveText('(in 0 / out 0)');
    await expect(page.locator('#account-summary #equity-chart')).toBeVisible();
    await expect(page.locator('#status-panel #agent-model')).toContainText('test · Connecting to account…');
    await expect(page.locator('#status-title')).toHaveText('Status');
    await expect(page.locator('.chat-heading')).not.toContainText('Account connected');
    await expect(page.locator('#holdings')).toBeVisible();
    await expect(page.locator('#activity')).toBeVisible();
    assert.ok((await page.locator('.metrics').boundingBox()).height < 95,'account indicators stay compact');
    assert.equal(await page.getByRole('tab',{name:'Conversation',exact:true}).count(),0,'conversation is part of Live');
    assert.ok((await page.locator('#positions').boundingBox()).y < 650,'positions appear near the top of Live');
    ui.setTraderActivity({state:'thinking',detail:'Reviewing MSFT exposure before the next decision.'});
    ui.log('INFO','Checking current positions and broker protection.');
    await expect(page.locator('#current-agents')).toContainText('Reviewing MSFT exposure');
    await expect(page.locator('#live-feed')).toContainText('Checking current positions and broker protection.');
    await page.getByRole('button',{name:'Focus conversation'}).click();
    await expect(page.locator('#welcome')).toBeVisible();
    assert.equal(await page.locator('#activity').evaluate(el=>getComputedStyle(el).position),'static');
    await page.getByRole('button',{name:'Get the bigger picture'}).click();
    await expect(page.locator('#message-text')).toHaveValue('How is my portfolio doing?');
    assert.equal(require('../src/core/requests').listRequests().length,1,'starter prepares a question without submitting it');
    await page.locator('#message-text').fill('');
    await page.getByRole('button',{name:'Switch to light theme'}).click();
    await expect(page.locator('html')).toHaveAttribute('data-theme','light');
    await page.reload();
    await expect(page.locator('html')).toHaveAttribute('data-theme','light');
    await page.getByRole('button',{name:'Switch to dark theme'}).click();
    await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
    asAssistant(() => ui.reply('Your account is **ready for review**.\n\n### Portfolio context\n- Check `MSFT` concentration.\n- <img src=x onerror=alert(1)>'));
    await expect(page.locator('#welcome')).toBeHidden();
    await expect(page.locator('.reply-body strong')).toHaveText('ready for review');
    await expect(page.locator('.reply-body h3')).toHaveText('Portfolio context');
    await expect(page.locator('.reply-body li')).toHaveCount(2);
    await expect(page.locator('.reply-body img')).toHaveCount(0);
    await expect(page.locator('.reply-body')).toContainText('<img src=x onerror=alert(1)>');
    await page.getByRole('tab',{name:'Live',exact:true}).click();
    await page.locator('#watchlist-rows button').first().click();
    await expect(page.locator('#ticker-chart-dialog')).toBeVisible();
    await expect(page.locator('#ticker-chart-title')).toHaveText('AAPL');
    await expect(page.locator('#ticker-chart .price-candle')).toHaveCount(3);
    await page.getByRole('button',{name:'Trend',exact:true}).click();
    await expect(page.locator('#ticker-chart .price-trend')).toHaveCount(1);
    await expect(page.locator('#ticker-chart .price-candle')).toHaveCount(0);
    await page.locator('#ticker-chart').focus();await page.locator('#ticker-chart').press('Home');
    await expect(page.locator('#ticker-ohlc > div').nth(1).locator('strong')).toHaveText('$100.00');
    await page.locator('#ticker-chart').press('End');
    await expect(page.locator('#ticker-ohlc > div').nth(1).locator('strong')).toHaveText('$101.00');
    await page.locator('#ticker-interval').selectOption('1Hour');
    await expect(page.locator('#ticker-chart')).toHaveAttribute('aria-label',/1Hour/);
    await page.getByRole('button',{name:'Candles',exact:true}).click();
    await expect(page.locator('#ticker-chart .price-candle')).toHaveCount(3);
    await page.locator('#ticker-chart-dialog').screenshot({path:'/tmp/autotrade-ticker-chart-desktop.png'});
    await page.getByRole('button',{name:'Discuss with agent'}).click();
    await expect(page.getByRole('tab',{name:'Live',exact:true})).toHaveAttribute('aria-selected','true');
    await expect(page.locator('#message-text')).toHaveValue('What is your current view on AAPL?');
    await page.locator('#message-text').fill('');
    await expect(page.locator('#account-mode')).toHaveText('paper');
    await page.getByRole('tab',{name:'Live',exact:true}).click();
    await page.locator('#positions').getByRole('button',{name:'Ask the agent about MSFT'}).click();
    await expect(page.locator('#message-text')).toHaveValue('How is MSFT doing, and what is your plan for it?');
    await page.getByRole('tab',{name:'Live',exact:true}).click();
    await expect(page.locator('#positions')).toContainText('+$15.00');
    // A new tick reaches the page through the event stream and extends the equity chart.
    await new Promise(resolve=>setTimeout(resolve,5));tick(100250,420);ui.setTick({});
    await expect(page.locator('#equity-change')).toContainText('+$250.00');
    await expect(page.locator('#equity-chart path')).toHaveCount(2);
    await page.getByRole('button',{name:'Approve action'}).click();
    await page.waitForFunction(()=>document.querySelector('#actions').textContent.includes('approved'));
    const actionRow = page.locator('#actions .timeline details').first();
    await actionRow.locator('summary').click();
    await expect(actionRow.locator('.action-facts dt')).toHaveText(['Quantity','Filled','Price','Stop','Target']);
    await expect(actionRow.locator('.action-facts dd')).toHaveText(['2','Not recorded','$100.00','$95.00','$110.00']);
    await expect(actionRow.locator('.action-references')).toContainText(p.id);
    await expect(actionRow.locator('.action-rationale')).toHaveText('Test action for browser verification');
    await expect(actionRow.locator('summary .reason')).toBeHidden();
    await expect(actionRow.locator('pre')).toHaveCount(0);
    await page.evaluate(() => refresh());
    await expect(actionRow).toHaveAttribute('open', '');
    assert.equal(require('../src/core/actions').getAction(p.id).actorId,'operator');
    await page.getByRole('tab',{name:'Activity',exact:true}).click();
    await expect(page.locator('#view-activity .history-row')).toHaveCount(4);
    await expect(page.locator('#history-decision-rows')).toContainText('approved');
    await expect(page.locator('#history-fill-rows')).toContainText('Not reported');
    await expect(page.locator('#history-event-rows .history-row')).toHaveCount(2);
    await expect(page.locator('#history-event-rows .history-row').first()).toContainText('Queued');
    await expect(page.locator('#history-event-rows .history-row').first()).toContainText('observed');
    await expect(page.locator('#history-event-rows .history-row').last()).toContainText('resolved');
    assert.ok((await page.locator('#history-event-title').boundingBox()).y > (await page.locator('#history-fill-title').boundingBox()).y);
    await page.locator('#history-event-rows .history-row-toggle').first().click();
    await expect(page.locator('#history-event-rows .history-expanded').first()).toContainText('The plan is below the required reward:risk.');
    await expect(page.locator('#history-event-rows .history-expanded').first()).toContainText('109.78');
    await expect(page.locator('#history-event-rows .history-expanded').first().locator('td')).toHaveAttribute('colspan','8');
    await page.getByRole('button',{name:'Refresh history'}).click();
    await expect(page.locator('#history-event-rows .history-row-toggle').first()).toHaveAttribute('aria-expanded','true');
    await page.locator('#history-event-rows .history-row-toggle').first().click();
    assert.ok((await page.locator('#history-decision-rows .history-row').boundingBox()).height < 40);
    await page.locator('#history-decision-rows .history-row-toggle').focus();
    await page.locator('#history-decision-rows .history-row-toggle').press('Enter');
    await expect(page.locator('#history-decision-rows .history-expanded')).toBeVisible();
    await expect(page.locator('#history-decision-rows')).toContainText('Action timeline');
    await page.getByRole('button',{name:'Refresh history'}).click();
    await expect(page.locator('#history-decision-rows .history-row-toggle')).toHaveAttribute('aria-expanded','true');
    await page.locator('#history-decision-rows .history-row-toggle').click();
    await expect(page.locator('#history-decision-rows .history-expanded')).toBeHidden();
    await page.screenshot({path:'/tmp/autotrade-activity-desktop.png',fullPage:true});
    await page.locator('#history-search').fill('no-matching-history');
    await expect(page.locator('#history-status')).toHaveText('No records match these filters.');
    await page.reload();
    await expect(page.getByRole('tab',{name:'Activity',exact:true})).toHaveAttribute('aria-selected','true');
    await expect(page.locator('#view-activity .history-row')).toHaveCount(4);
    await page.getByRole('tab',{name:'Live',exact:true}).click();
    await page.getByRole('button',{name:'Pause trading',exact:true}).click();
    await page.getByRole('button',{name:'Resume trading',exact:true}).waitFor();assert.equal(getState().paused,true);
    await page.getByRole('tab',{name:'Strategy'}).click();
    const originalSymbols=[...getPolicySnapshot().policy.strategy.watchlist];
    await expect(page.locator('#allowed-symbols .symbol-tag')).toHaveCount(originalSymbols.length);
    await page.getByRole('textbox',{name:'Symbol to add'}).fill('tagtest');
    await page.getByRole('textbox',{name:'Symbol to add'}).press('Enter');
    await expect(page.getByRole('button',{name:'Remove TAGTEST',exact:true})).toBeVisible();
    await expect(page.locator('#review')).toBeHidden();
    await page.getByRole('textbox',{name:'Symbol to add'}).fill('TAGTEST');
    await page.getByRole('button',{name:'Add',exact:true}).click();
    await expect(page.locator('#allowed-symbols .symbol-tag')).toHaveCount(originalSymbols.length+1);
    await expect(page.locator('#symbol-feedback')).toContainText('already in the list');
    await page.getByRole('textbox',{name:'Symbol to add'}).fill('BAD/SYM');
    await page.getByRole('button',{name:'Add',exact:true}).click();
    await expect(page.getByRole('textbox',{name:'Symbol to add'})).toHaveAttribute('aria-invalid','true');
    await expect(page.locator('#allowed-symbols .symbol-tag')).toHaveCount(originalSymbols.length+1);
    await page.getByRole('textbox',{name:'Symbol to add'}).fill('');
    await page.getByRole('button',{name:`Remove ${originalSymbols[0]}`,exact:true}).click();
    await expect(page.locator('#allowed-symbols .symbol-tag')).toHaveCount(originalSymbols.length);
    assert.deepEqual(getPolicySnapshot().policy.strategy.watchlist,originalSymbols,'tag edits remain drafts until the strategy is saved');
    await page.locator('.symbol-field').screenshot({path:'/tmp/autotrade-allowed-symbols-desktop.png'});
    await page.getByLabel('Maximum positions',{exact:true}).fill('2');
    const profileRevision=getPolicySnapshot().hash;
    await page.getByLabel('Profile',{exact:true}).selectOption('conservative');
    assert.equal(await page.getByLabel('Risk per trade (% of equity)',{exact:true}).inputValue(),'0.25');
    assert.equal(await page.getByLabel('Portfolio volatility target (% per year)',{exact:true}).inputValue(),'8');
    assert.equal(await page.getByLabel('Maximum position size (%)',{exact:true}).inputValue(),'5');
    assert.equal(getPolicySnapshot().hash,profileRevision,'editing a preset does not activate it');
    await page.getByLabel('Risk per trade (% of equity)',{exact:true}).fill('0.35');
    assert.equal(await page.getByLabel('Profile',{exact:true}).inputValue(),'custom');
    await page.getByRole('button',{name:'Review and save',exact:true}).click();
    assert.match(await page.locator('#review-text').textContent(),/Risk per trade: 0.5% → 0.35%/);
    await page.getByRole('button',{name:'Save this revision',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#settings-state').textContent==='Saved');
    assert.equal(getPolicySnapshot().policy.risk.riskPerTradePct,0.35);
    assert.equal(getPolicySnapshot().policy.risk.targetVolatilityPct,8);
    assert.deepEqual(getPolicySnapshot().policy.strategy.watchlist,[...originalSymbols.slice(1),'TAGTEST']);
    await page.getByRole('button',{name:'Reload saved settings',exact:true}).click();
    assert.equal(await page.getByLabel('Profile',{exact:true}).inputValue(),'custom');
    await expect(page.getByRole('button',{name:'Remove TAGTEST',exact:true})).toBeVisible();
    await expect(page.getByRole('button',{name:`Remove ${originalSymbols[0]}`,exact:true})).toHaveCount(0);
    await page.locator('.risk-profile').screenshot({path:'/tmp/autotrade-risk-profile-desktop.png'});
    await page.getByRole('tab',{name:'Review'}).click();
    await expect(page.locator('#scorecard')).toContainText('Completed trades');
    await expect(page.locator('#lesson-list .history-expanded')).toBeHidden();
    await page.locator('#lesson-list .history-row-toggle').click();
    await expect(page.locator('#lesson-list .history-expanded')).toBeVisible();
    await page.locator('#lesson-list textarea').fill('Review measured concentration before adding exposure.');
    await page.locator('#lesson-list').getByRole('button',{name:'Save',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#lesson-list textarea').value.startsWith('Review measured'));
    await page.locator('#lesson-list').getByRole('button',{name:'Retire',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#lesson-list').textContent.includes('Retired'));
    assert.equal(lessons.listLessons()[0].active,false);
    assert.match(await page.locator('#agent-commands').textContent(),/operator/);
    await page.locator('#agent-commands .history-row-toggle').first().click();
    await expect(page.locator('#agent-commands .history-expanded').first()).toBeVisible();
    await expect(page.locator('#agent-commands .request-detail').first()).not.toContainText('Request record');
    assert.ok((await page.locator('#agent-commands .request-detail').first().boundingBox()).height < 170,'expanded request remains compact');
    await page.locator('#requests').screenshot({path:'/tmp/autotrade-request-compact.png'});
    await page.locator('#agent-commands .history-row-toggle').first().click();
    await expect(page.locator('#agent-commands .history-expanded').first()).toBeHidden();
    await page.locator('#lesson-list .history-row-toggle').click();
    await page.screenshot({path:'/tmp/autotrade-review-tables.png',fullPage:true});
    await page.getByRole('tab',{name:'Live'}).click();
    await page.locator('#message-text').fill('What is the request status?');
    await page.locator('#message').getByRole('button',{name:'Send',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('queued'));
    await expect(page.locator('#feed .msg.operator').last()).toContainText('What is the request status?');
    const input=page.getByRole('combobox',{name:'Message'}),menu=page.getByRole('listbox',{name:'Commands'});
    const queuedBefore=require('../src/core/requests').listRequests().length;
    await input.fill('/');
    await expect(menu).toBeVisible();
    await expect(menu.getByRole('option')).toHaveCount(4);
    await expect(input).toHaveAttribute('aria-expanded','true');
    await input.press('ArrowDown');
    await expect(menu.getByRole('option',{selected:true})).toContainText('/pause');
    await input.press('Enter');
    await expect(input).toHaveValue('/pause ');
    await expect(menu).toBeHidden();
    assert.deepEqual(commandRuns,['pause'],'selecting does not run the command');
    await input.fill('/LE');
    await expect(menu.getByRole('option')).toHaveCount(1);
    await expect(menu).toContainText('/lessons [n]');
    await input.press('Tab');
    await expect(input).toHaveValue('/lessons ');
    await expect(input).toBeFocused();
    await input.pressSequentially('2');
    await expect(menu).toBeHidden();
    await input.press('Enter');
    await expect(input).toHaveValue('');
    await expect(page.locator('#live-feed')).toContainText('Lessons requested: 2');
    await expect(page.locator('#feed')).not.toContainText('Lessons requested: 2');
    await expect(page.locator('#live-feed .activity-entry.operator').last().locator('.activity-entity')).toHaveText('You');
    await expect(page.locator('#live-feed .activity-entry.operator').last().locator('.activity-kind')).toHaveText('[COMMAND]');
    assert.equal(commandRuns.at(-1),'lessons 2');
    await input.fill('/pos');
    await expect(menu.getByRole('option')).toHaveCount(1);
    await input.press('Escape');
    await expect(menu).toBeHidden();
    await expect(input).toHaveValue('/pos');
    await input.press('ArrowDown');
    await menu.getByRole('option').click();
    await expect(input).toHaveValue('/positions ');
    await input.press('Enter');
    await expect(page.locator('#live-feed')).toContainText('Positions command complete.');
    await expect(page.locator('#feed')).not.toContainText('Positions command complete.');
    await expect(input).toHaveValue('');
    await input.fill('/');
    await input.press('ArrowUp');
    await expect(menu.getByRole('option',{selected:true})).toContainText('/lessons');
    await input.press('Escape');
    await input.fill('What does /pause do?');
    await expect(menu).toBeHidden();
    await input.fill('/unknown');
    await expect(page.locator('#command-empty')).toBeVisible();
    await input.press('Enter');
    await expect(page.locator('#notice')).toContainText('Unknown or unavailable command');
    await expect(input).toHaveValue('/unknown');
    assert.equal(require('../src/core/requests').listRequests().length,queuedBefore,'slash commands never enter the assistant queue');
    await input.fill('/');
    await page.locator('#activity').screenshot({path:'/tmp/autotrade-slash-commands-desktop.png'});
    await input.press('Tab');
    await page.screenshot({path:'/tmp/autotrade-desktop.png',fullPage:true});
    asAssistant(() => ui.showChart({kind:'price',label:'IBM',values:[232.76,227.21,225,220.56,219.45,219.45,225,222.78,221.67,221.67,220.56,219.45],dates:['2026-09-23','2026-09-24','2026-09-25','2026-09-28','2026-09-29','2026-09-30','2026-10-01','2026-10-02','2026-10-05','2026-10-06','2026-10-07','2026-10-08']}));
    await expect(page.locator('.chat-series-plot .price-trend')).toHaveCount(1);
    assert.ok((await page.locator('.chat-series-plot').boundingBox()).width > 500,'short histories fill the desktop chat width');
    await page.locator('.chat-series-chart').screenshot({path:'/tmp/autotrade-chat-chart-desktop.png'});
    const mobileContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,storageState:await context.storageState()});
    const mobile=await mobileContext.newPage();
    await mobile.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
    await mobile.route('**/api/price-history?**',chartRoute);
    await mobile.goto(base);
    await mobile.locator('#workspace').waitFor({state:'visible'});
    await expect(mobile.locator('.chat-series-plot .price-trend')).toHaveCount(1);
    await mobile.locator('.chat-series-chart').screenshot({path:'/tmp/autotrade-chat-chart-mobile.png'});
    assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    await mobile.waitForTimeout(500);
    await expect(mobile.locator('#account-mode')).toBeVisible();
    await expect(mobile.locator('#account-mode')).toHaveText('paper');
    await mobile.screenshot({path:'/tmp/autotrade-mobile.png'});
    await mobile.locator('#positions').getByRole('button',{name:'View MSFT price chart',exact:true}).click();
    await expect(mobile.locator('#ticker-chart .price-candle')).toHaveCount(3);
    await mobile.locator('#ticker-chart-dialog').screenshot({path:'/tmp/autotrade-ticker-chart-mobile.png'});
    assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    await mobile.getByRole('button',{name:'Close price chart'}).click();
    await mobile.getByRole('tab',{name:'Activity',exact:true}).click();
    await expect(mobile.locator('#view-activity .history-row')).toHaveCount(4);
    await mobile.screenshot({path:'/tmp/autotrade-activity-mobile.png',fullPage:true});
    assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    await mobile.getByRole('tab',{name:'Live',exact:true}).click();
    await mobile.locator('#holdings').screenshot({path:'/tmp/autotrade-mobile-holdings.png'});
    assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    await mobile.getByRole('tab',{name:'Review'}).click();
    await mobile.locator('#lessons').screenshot({path:'/tmp/autotrade-mobile-lessons.png'});
    await mobile.getByRole('tab',{name:'Strategy'}).click();
    await expect(mobile.getByRole('button',{name:'Remove TAGTEST',exact:true})).toBeVisible();
    await mobile.locator('.symbol-field').screenshot({path:'/tmp/autotrade-allowed-symbols-mobile.png'});
    await mobile.locator('.risk-profile').screenshot({path:'/tmp/autotrade-risk-profile-mobile.png'});
    assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    await mobile.getByRole('tab',{name:'Live'}).click();
    await mobile.locator('#message-text').fill('/');
    await expect(mobile.getByRole('listbox',{name:'Commands'})).toBeVisible();
    await mobile.locator('#activity').screenshot({path:'/tmp/autotrade-slash-commands-mobile.png'});
    assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    await mobile.getByRole('option').filter({hasText:'/positions'}).tap();
    await expect(mobile.locator('#message-text')).toHaveValue('/positions ');
    await expect(mobile.getByRole('listbox',{name:'Commands'})).toBeHidden();
    await mobileContext.close();
    asAssistant(() => ui.showChart({kind:'comparison',a:{label:'IBM',values:[100,120,110]},b:{label:'SPY',values:[100,95,100]}}));
    await expect(page.locator('.chat-series-plot .price-trend')).toHaveCount(3);
    assert.deepEqual(await page.locator('.chat-series-plot').nth(1).locator('.price-axis').allTextContents(),await page.locator('.chat-series-plot').nth(2).locator('.price-axis').allTextContents(),'comparison charts share a percent scale');
    assert.deepEqual(errors,[]);
  } finally {await browser?.close();await server.close();closeStorage();}
});
